sentry:
    dsn: '%env(SENTRY_DSN)%'
    register_error_listener: false # Disables the ErrorListener to avoid duplicated log in sentry
    options:
        error_types: E_ALL
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'

monolog:
    handlers:
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::ERROR
            hub_id: Sentry\State\HubInterface
        file_log:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
